export type MovieType = {
  id: number;
  adult?: boolean | null;
  budget?: number | null;
  production_companies?: string | null;
  production_countries?: string | null;
  belongs_to_collection?: string | null;
  genres?: string | null;
  spoken_languages?: string | null;
  homepage?: string | null;
  imdb_id: string;
  original_language: string;
  original_title: string;
  overview?: string | null;
  popularity?: string | null;
  poster_path?: string | null;
  release_date?: string | null;
  revenue?: string | null;
  runtime?: string | null;
  status: string;
  tagline?: string | null;
  title: string;
  video: boolean;
  vote_average?: string | null;
  vote_count?: string | null;
};
